sudo: false
language: go
go: 
  - 1.10.x
  - release
  - tip

notifications:
  email:
    - rcmonnet@gmail.com
 
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
